duration = 200
seed = "I peed myself in the library!?"

[wait_time_distribution]
method = "exponential"
args = {scale = 10}

[videos]
count = 100

[videos.quality_distribution]
method = "normal"

[rating]
method = "step"
args = {width = 10}

[[users]]
count = 20

[users.selection]
method = "probability"

[users.bias]
method = "quality with rating saturation"
args = {scale = 1, alpha = 0.5, offset = 8}
